[package]
name = "map-array-sys"
version.workspace = true
edition.workspace = true

[dependencies]
lean-sys = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
examples-build-infrastructure = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
lean = { workspace = true }
