name = "pure_lean"
version = "0.1.0"

[[lean_lib]]
name = "Sleeper"
buildType = "release"
defaultFacets = ["static"]

[[lean_exe]]
name = "concurrent"
root = "Concurrent"

[[lean_exe]]
name = "sequential"
root = "Sequential"
