[package]
name = "async-effect-sys"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-effect-ffi = { workspace = true }
lean-sys = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
examples-build-infrastructure = { workspace = true }
