name = "map-array-bin"
versionTags = []
defaultTargets = ["main"]
licenseFiles = ["../../../../LICENSE-APACHE", "../../../../LICENSE-MIT"]

[[lean_exe]]
name = "main"
buildType = "release"
root = "Main"

[[require]]
name = "map-array"
path = "../map_array"
