[package]
name = "lean"
version.workspace = true
edition.workspace = true

[dependencies]
lean-derive = { workspace = true, optional = true }
lean-macro = { workspace = true, optional = true }
lean-sys = { workspace = true }
thiserror = { workspace = true }

[features]
derive = ["lean-derive"]
macro = ["lean-macro"]
