[package]
name = "sleeper-lean"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
# TODO replace async-effect* dependencies with dependencies on sleeper-sys
async-effect-ffi = { workspace = true }
async-effect-sys = { workspace = true }
concurrent-sys = { workspace = true }
lean = { workspace = true }
lean-sys = { workspace = true }
sequential-sys = { workspace = true }
